feat: add eslint
ONLYOFFICE/onlyoffice-zapier pull request #2
Opened 2023-11-23 08:11 UTC by ZEROM22

2023-11-23 11:31 UTC, vanyauhalin requested changes

2023-11-23 11:31 UTC, vanyauhalin commented on makefile.js
> +
You don't have to wrap the ESLint commands in the Makefile. Simply add `eslint` to the `package.json` scripts:

```sh
$ cat ./package.json | jq .scripts
{
  "lint": "eslint ."
}
```

Then execute it:

```sh
$ pnpm lint
# or
$ pnpm lint --fix
```

2023-11-23 11:31 UTC, vanyauhalin commented on .eslintrc.json
Their comments don't reflect your personal opinion or provide any additional information. They simply repeat everything that can be found in the ESLint's documentation. I recommend deleting them.

2023-11-23 13:22 UTC, vanyauhalin commented
Additionally, please rename the `.eslintrc.json` to `eslint.config.js`. Also, add the `@stylistic/eslint-plugin-js` as a dependency.

Read more about the file [here](https://eslint.org/docs/latest/use/configure/configuration-files-new), and about the dependency [here](https://eslint.style/guide/why).

2023-11-23 13:42 UTC, vanyauhalin commented
> Additionally, please rename the `.eslintrc.json` to `eslint.config.js`. Also, add the `@stylistic/eslint-plugin-js` as a dependency.
> 
> Read more about the file [here](https://eslint.org/docs/latest/use/configure/configuration-files-new), and about the dependency [here](https://eslint.style/guide/why).

And please migrate to the flat config. Read more [here](https://eslint.org/docs/latest/extend/plugin-migration-flat-config).

2023-11-27 10:35 UTC, ZEROM22 commented
> Additionally, please rename the `.eslintrc.json` to `eslint.config.js`. Also, add the `@stylistic/eslint-plugin-js` as a dependency.
> 
> Read more about the file [here](https://eslint.org/docs/latest/use/configure/configuration-files-new), and about the dependency [here](https://eslint.style/guide/why).

I added `@stylistic/eslint-plugin-js' and rewrote the config to flat.

2023-11-28 05:08 UTC, vanyauhalin approved these changes

2023-11-29 08:02 UTC, vanyauhalin commented
@ZEROM22, please resolve conflicts.

2023-11-29 11:19 UTC, merged