feat: add file download action
ONLYOFFICE/onlyoffice-zapier pull request #43
Opened 2023-12-28 11:43 UTC by ZEROM22

2024-01-10 22:02 UTC, ZEROM22 commented on app/hydrators.js
> + * @param {{ inputData: { url: string; }; }} bundle // TODO Bundle<SessionAuthenticationData, InputData> not work
@vanyauhalin Please help with JSDoc

2024-01-11 07:58 UTC, vanyauhalin requested changes

2024-01-11 07:58 UTC, vanyauhalin commented on app/hydrators.js
> + * @param {{ inputData: { url: string; }; }} bundle // TODO Bundle<SessionAuthenticationData, InputData> not work
```js
/**
 * @typedef {Object} InputData
 * @property {string} url
 */

/**
 * @param {ZObject} z
 * @param {Bundle<SessionAuthenticationData, InputData>} bundle
 * @returns {Promise<string>}
 */
```

2024-01-12 08:52 UTC, vanyauhalin approved these changes

2024-01-12 08:52 UTC, vanyauhalin commented on app/zapier/files/triggers.js
> +      } else if (!bundle.inputData.folderId) {
You can omit the `else` keyword here.

2024-01-12 09:54 UTC, merged